## -*- mode: makefile -*-

##
## This file is part of the Score-P software (http://www.score-p.org)
##
## Copyright (c) 2009-2012,
## RWTH Aachen University, Germany
##
## Copyright (c) 2009-2012,
## Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
##
## Copyright (c) 2009-2012, 2022,
## Technische Universitaet Dresden, Germany
##
## Copyright (c) 2009-2012,
## University of Oregon, Eugene, USA
##
## Copyright (c) 2009-2013,
## Forschungszentrum Juelich GmbH, Germany
##
## Copyright (c) 2009-2012,
## German Research School for Simulation Sciences GmbH, Juelich/Aachen, Germany
##
## Copyright (c) 2009-2012,
## Technische Universitaet Muenchen, Germany
##
## This software may be modified and distributed under the terms of
## a BSD-style license.  See the COPYING file in the package base
## directory for details.
##

## file       test/instrumenter_checks/Makefile.common_rules

all:

#------------------------------------------------------------------------------
# Common rules to instrument codes using the instrumenter-checks rule
#------------------------------------------------------------------------------

include $(INSTRUMENTERCHECK_SRCDIR)/Makefile.common_rules_base

$(BINDIR)/$(CODE)-$(PARADIGM)-cc$(SUFFIX): $(OBJECTS) $(TOOLS)
	$(SCOREP_V_CCLD)$(PREP) $(SCOREP_V_verbose) $(CC) $(CFLAGS) -o $@ $(OBJECTS) $(LIBS) $(LIBS_INTERNAL)

$(BINDIR)/$(CODE)-$(PARADIGM)-cxx$(SUFFIX): $(OBJECTS) $(TOOLS)
	$(SCOREP_V_CXXLD)$(PREP) $(SCOREP_V_verbose) $(CXX) $(CXXFLAGS) -o $@ $(OBJECTS) $(LIBS) $(LIBS_INTERNAL)

$(BINDIR)/$(CODE)-$(PARADIGM)-f77$(SUFFIX): $(OBJECTS) $(TOOLS)
	$(SCOREP_V_F77LD)$(PREP) $(SCOREP_V_verbose) $(F77) $(F77FLAGS) -o $@ $(OBJECTS) $(LIBS) $(LIBS_INTERNAL)

$(BINDIR)/$(CODE)-$(PARADIGM)-fc$(SUFFIX): $(OBJECTS) $(TOOLS)
	$(SCOREP_V_FCLD)$(PREP) $(SCOREP_V_verbose) $(FC) $(FCFLAGS) -o $@ $(OBJECTS) $(LIBS) $(LIBS_INTERNAL)

$(BINDIR)/$(CODE)-$(PARADIGM)-cu$(SUFFIX): $(OBJECTS) $(TOOLS)
	$(SCOREP_V_NVCCLD)$(PREP) $(SCOREP_V_verbose) $(NVCC) -ccbin $(CXX) $(CUFLAGS) $(CXXFLAGS) -o $@ $(OBJECTS) $(LIBS) $(LIBS_INTERNAL)

$(OBJDIR)/%.o: $(SRCDIR)/%.c $(TOOLS)
	$(SCOREP_V_CC)$(PREP) $(SCOREP_V_verbose) $(CC) $(CFLAGS) -o $@ -c $<

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp $(TOOLS)
	$(SCOREP_V_CXX)$(PREP) $(SCOREP_V_verbose) $(CXX) $(CXXFLAGS) -o $@ -c $<

$(OBJDIR)/%.o: $(SRCDIR)/%.f77 $(TOOLS)
	$(SCOREP_V_F77)$(PREP) $(SCOREP_V_verbose) $(F77) $(F77FLAGS) -o $@ -c $<

$(OBJDIR)/%.o: $(SRCDIR)/%.f90 $(TOOLS)
	$(SCOREP_V_FC)$(PREP) $(SCOREP_V_verbose) $(FC) $(FCFLAGS) -o $@ -c $<

$(OBJDIR)/%.o: $(SRCDIR)/%.F90 $(TOOLS)
	$(SCOREP_V_FC)$(PREP) $(SCOREP_V_verbose) $(FC) $(FCFLAGS) -o $@ -c $<

$(OBJDIR)/%.o: $(SRCDIR)/%.cu $(TOOLS)
	$(SCOREP_V_NVCC)$(PREP) $(SCOREP_V_verbose) $(NVCC) -ccbin $(CXX) $(CUFLAGS) $(CXXFLAGS) -o $@ -c $<
